
export const UPDATE_BUSINESS_DATA = 'UPDATE_BUSINESS_DATA'
export const UPDATE_DIRECTOR_DATA = 'UPDATE_DIRECTOR_DATA'
export const UPDATE_APPLICANT_DATA = 'UPDATE_APPLICANT_DATA'
export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION'
export const ALL_USER_DATA = 'ALL_USER_DATA'

const userActions = Object.freeze({
  ALL_USER_DATA,
  UPDATE_BUSINESS_DATA,
  UPDATE_DIRECTOR_DATA,
  UPDATE_APPLICANT_DATA,
  SUBMIT_APPLICATION
})

export default userActions
